Module2 task1
htmlacademy-adaptive/2057907-cat-energy-26 pull request #2
Opened 2022-07-29 14:16 UTC by byebyesad

Завершает разметку всех страниц

2022-07-30 17:08 UTC, Zakamsky requested changes
В целом все добротно, вижу что работа проделана старательна, информация по нжйминга БЭМ'a воспринятиа корректно но кое где выползли ошибки.

В целом ты везеде используешь модификаторы корректно, но на внутренних страницах, в меню, видимо при копипасте промазал...

Поля в форме не стал сейчас отмечать как обязательные к правке, но надо будет их когда то привести в корректный вид.

2022-07-30 17:08 UTC, Zakamsky commented on source/index.html
> +        <div class="main-nav__list logo-list">
а что это за `list` список какой то?

2022-07-30 17:08 UTC, Zakamsky commented on source/index.html
> +              alt="Логотип интернет-магазина функционального питания для котов «Cat Energy»">
если это половинка лого, то лучше ее скрыть от читалок а не "повторять, повторять"

2022-07-30 17:08 UTC, Zakamsky commented on source/index.html
> +          <li class="site-list__item site-list__item--current">
отличное понмиание модификаторов!

2022-07-30 17:08 UTC, Zakamsky commented on source/index.html
> +              alt="Стройный кот">
У меня большие сомнения что это изображение несет какую то смысловую нагрузку, это точно контент, а не иконочка для красоты? Если скажем завтра ее заменят, смысл окружения поменяется?

2022-07-30 17:08 UTC, Zakamsky commented on source/index.html
> +        <ul class="advantages__list">
а зачем тут вообще див, мы не сможем сам список стилизовать так же?

2022-07-30 17:08 UTC, Zakamsky commented on source/index.html
> +      <div class="features__wrapper">
В целом везде где нет фона на всю ширину мы можем заузить саму секцию, не добавляя дополнительные дивы.
з.ы. я не сомтрел тут в макет т.ч. это комментарий в целом для понимания. Может этот дви и нужен...

2022-07-30 17:08 UTC, Zakamsky commented on source/index.html
> +            <span class="features__number">1</span>
Эти цифры лучше добавить стилевыми счетчиками, они довольно просто делаются. Я помогу разобраться потом.

2022-07-30 17:08 UTC, Zakamsky commented on source/index.html
> +        <div class="comparison__controls">
этот элемент находится снаружи своего блока, так не должно быть, это нарушения БЭМ.

2022-07-30 17:08 UTC, Zakamsky commented on source/index.html
> +        </div>
нам не нужна тут карта в контенте, у нас есть интерактивный экземпляр. Но что бы не сломался интерфейс, при отсутсвии js, мы можем эту же карту картинкой повесить стилями на фон `.cooperation__map-wrapper`

2022-07-30 17:08 UTC, Zakamsky commented on source/index.html
> +        </div>
upd: это актуально для всех страниц.

2022-07-30 17:08 UTC, Zakamsky commented on source/index.html
> +              <span class="visually-hidden">Мы в Вконтакте</span>
тут все отлично и ты классно работаешь с модификаторами.
но найди пожалуйста в чате видео про маски.
Мы потом будем делать свг спрайты, и их мы тоже сможем вывести масками из стилей не загрязняя разметку.

2022-07-30 17:08 UTC, Zakamsky commented on source/index.html
> +        <p class="cooperation__description">Ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</p>
есть кстати калссны тэг `address`

2022-07-30 17:08 UTC, Zakamsky commented on source/catalog.html
> +          </li>
тут модивикатор явно не на месте, возможно прото опечатка, что мы все таки модифицируем, `link` или `item`?

2022-07-30 17:08 UTC, Zakamsky commented on source/catalog.html
> +          </li>
upd: а мы что сразу на двух страницах находимся?

2022-07-30 17:08 UTC, Zakamsky commented on source/catalog.html
> +                alt="Cat Energy Pro со вкусом курицы, 500 грамм">
а как мы `.jpg` будем на серый фон натягивать?

2022-07-30 17:08 UTC, Zakamsky commented on source/catalog.html
> +                      Масса
У меня к карточке товара возникает ряд вопросов:
- где название товара?
- есть ли у нас ссылка на страницу товара, и если есть, то где она?
- кнопку заказать лучше сделать ссылкой, даже если она открывает попап, в случае поломки скриптов, она отправит пользовтаеля в корзину для покупки этого товара.

2022-07-30 17:08 UTC, Zakamsky commented on source/catalog.html
> +        </div>
А вот тут у нас скорее всего не изображение конкретного товара, а просто картинка для красоты. которое лучше добавить фоном, или псевдоэлементом

2022-07-30 17:08 UTC, Zakamsky commented on source/form.html
> +            <a class="site-list__link  site-list__item--current">
опять мы не то модифицируем, и опять на двух страницах сразу...

2022-07-30 17:08 UTC, Zakamsky commented on source/form.html
> +            </label>
точно ли рост и возраст, это текстовая информация?

2022-07-30 17:08 UTC, Zakamsky commented on source/form.html
> +                <input class="program-form__field program-form__field--icon" type="text" name="email"
я сейчас могу отправить любой текст, а можно ыбло указать правильный тип поля и бразер сам бы проверил что введен корректный емайл.

2022-07-30 17:08 UTC, Zakamsky commented on source/form.html
> +                <input class="program-form__field program-form__field--icon" type="text" name="phone"
для телефона тоже есть отдельный тип поля.

2022-07-30 17:08 UTC, Zakamsky commented on source/form.html
> +          <button class="program-form__button button">Отправить заявку</button>
Имеет смысл всегда указывать тайп для кнопки что бы точно знать что мы не ошиблись.

2022-07-30 17:13 UTC, byebyesad commented on source/index.html
> +        <div class="main-nav__list logo-list">
Ну, в демо было нечто похожее, там объяснялось, чтобы не было второй список с одним пунктом, можно просто дивом

2022-07-30 17:21 UTC, byebyesad commented on source/index.html
> +            <span class="features__number">1</span>
В данном случае для этого требуется удалить спан создать дополнительный класс к p?

2022-07-30 18:49 UTC, byebyesad commented on source/index.html
> +              alt="Логотип интернет-магазина функционального питания для котов «Cat Energy»">
через атрибут aria-hidden?

2022-07-30 18:53 UTC, byebyesad commented on source/index.html
> +              alt="Стройный кот">
Я долго думал над этим и сделал неверное решение :( У меня сложности бывают с понимаем контентного с неявным декором (все статьи читал из учебника на этот счет читал)

2022-07-30 19:04 UTC, byebyesad commented on source/form.html
> +            </label>
Не смог придумать название по смыслу объединяющее имя, вес и возраст

2022-07-31 00:09 UTC, byebyesad commented on source/index.html
> +              <span class="visually-hidden">Мы в Вконтакте</span>
Посмотрел, круто)

2022-07-31 00:32 UTC, byebyesad commented on source/index.html
> +        <p class="cooperation__description">Ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</p>
Совсем про него забыл... 
Если я правильно понимаю address в нём может быть в данном случае только сам адрес, так? Ещё вопрос немного не по этому комменту: я переместил карту из блока cooperation, потому что карта должна будет тянуться на всю ширину экрана. То есть, футер - серый фон на всю ширину, секция - ограничения для контента, блок локация - на всю ширину родителя (то есть футера, на всю ширину экрана). Посмотрите, так верно?
```
<footer class="main-footer">
    <section class="main-footer__cooperation cooperation">
      <h2 class="cooperation__title">Приглашаем к сотрудничеству дилеров!</h2>
      <address class="cooperation__address">
        <p class="cooperation__address-text">Ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</p>
      </address>
    </section>
    <div class="main-footer-location location">
      <iframe class="location__map"
        src="https://yandex.ru/map-widget/v1/?um=constructor%3A95450451a50e191e02d00f00296c7e42715b26db23d44613b3393d2eed27c4d6&amp;source=constructor"
        width="320" height="362"></iframe>
    </div>
```

2022-07-31 00:33 UTC, byebyesad commented on source/catalog.html
> +          </li>
Торопился, копировать-вставить, не уследил(

2022-07-31 00:36 UTC, byebyesad commented on source/catalog.html
> +                alt="Cat Energy Pro со вкусом курицы, 500 грамм">
Вспоминал 1 курс HTML. Там объясняли, мол, а что если потом контент-менеджер вставил jpg и всё сломается... Можете объяснить как вы считаете? Я понимаю насчет фона прекрасно, интересует как бывает в реальных проектах с этими менеджерами в данном случае...

2022-07-31 00:40 UTC, byebyesad commented on source/catalog.html
> +                      Масса
1) ой... я просто сначала делал название как capture таблицы, потом вы объяснили про таблицы, я удалил таблицу, исправил на dl, а про название забылось...

2) ссылки на страницу конкретного любого товара я нигде в макете не увидел...

3) Понял

2022-07-31 16:07 UTC, Zakamsky commented on source/index.html
> +              alt="Логотип интернет-магазина функционального питания для котов «Cat Energy»">
Тебе не кажется что было бы быстрее добавить этот атрибут, и если бы ты ошибся - я бы поправил?
Но вообще ты прав.

2022-07-31 16:10 UTC, Zakamsky commented on source/index.html
> +              alt="Стройный кот">
ну вот я пытаюсь дать наводку - если это важный смысл несет, например продает товар, или иллюстрирует статью. И смена изображения поменяет градус понимания окружающего блока - это контент.
Если это не несет смысла и мы поменяем на похожую картинку в другом стиле - и ничего не сломаем - это оформление.

То что ты ошибся не страшно. просто подумай еще раз, запомни сделанные выводы, и исправь.

2022-07-31 21:23 UTC, Zakamsky commented on source/index.html
> +        <div class="main-nav__list logo-list">
можно что угодно, но если у нас не список то зfчем в классе `-list`?

2022-07-31 21:29 UTC, Zakamsky approved these changes
Отличная работа над ошибками, двигаемся дальше!

2022-07-31 21:29 UTC, Zakamsky commented on source/index.html
> +        <a class="logo-list__link" href="index.html">
так а чей это все таки элемент?
может блоком его просто сделать?

2022-07-31 21:29 UTC, merged